### ISSUE TITLE
make a sick design, brah

### ISSUE THREAD

**Issue by mmorehea** [mmorehea/syGlassPage#1]

**Comment by nathantspencer** [comment]
First attempt. Not digging the font too much.

![syglass1gray-01](https://cloud.githubusercontent.com/assets/12968782/15094256/61f66494-146c-11e6-969f-d81ef4ff0b2c.png)

**Comment by nathantspencer** [comment]
Path simplification and Ubuntu font!

![syglass2-01](https://cloud.githubusercontent.com/assets/12968782/15094361/0e5da330-146f-11e6-82f6-cd29b63a0cce.png)

**Comment by nathantspencer** [comment]
Much more abstract take on spyglass theme, featuring a trace of an actual mesh

![syglass3-01](https://cloud.githubusercontent.com/assets/12968782/15094572/47fc49e6-1476-11e6-85d2-2f50b0e9ab56.png)

**Comment by nathantspencer** [comment]
Wireframe edition!
![syglass4-01](https://cloud.githubusercontent.com/assets/12968782/15095392/d97b07de-1491-11e6-8b7f-a8fe84852165.png)
